package GUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.AbstractTableModel;

import IO.InOutException;
import model.AlreadyFavourite;
import model.AlreadyRated;
import model.DataHandler;
import model.Movie;
import model.RatingOutOfBound;

/**
 * Class functioning as a controller. It catches the events generated by the
 * view and executes the necessary operations on the model.
 * 
 * @author Tibor Salagvárdi
 */
public class Controller
{
	private MainWindow view;
	private DataHandler programModel;

	public Controller(MainWindow view, DataHandler state)
	{
		this.view = view;
		this.programModel = state;
		
		view.addSearchListenerForFavourites(new SearchInFavoritesListener());
		view.addSearchListenerForPublicDB(new SearchInDBListener());
		view.addShowAllFavoritesListener(new ShowAllFavorites());
		view.addMovieSelectionListener(new MovieSelectListener(view.getMovieTable(), view.getActorTable()));
		view.addActorSelectionListener(new ActorSelectListener(view.getMovieTable(), view.getActorTable()));
		view.addFavMovieSelectionListener(new MovieSelectListener(view.getFavMovieTable(), view.getFavActorTable()));

		view.addMovieRateListener(new MovieRateListener(view.getMovieTable(),programModel.getMovies()));
		view.addFavMovieRateListener(new MovieRateListener(view.getFavMovieTable(), programModel.getFavorites()));
		view.addRemoveListener(new RemoveListener());
		view.addSaveListener(new SaveListener());
		view.addTabListener(new TabListener());

	}

	public class SearchInDBListener implements ActionListener
	{
		public void actionPerformed(ActionEvent arg0)
		{
			if (view.getDataToSearchFor() == MainWindow.LOOKING_FOR_ACTOR)
			{
				try {
					programModel.loadActorsByName(view.getNameInPublicDB());
				} catch (InOutException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
				view.updateActorTable();
				view.updateFavActorTable();
			}
			else
			{
				try {
					programModel.loadMoviesByTitle(view.getNameInPublicDB());
				} catch (InOutException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
				view.updateMovieTable();
			}
		}
	}
	public class SearchInFavoritesListener implements ActionListener
	{
		public void actionPerformed(ActionEvent arg0)
		{
			programModel.filterFavorites(view.getNameInFavourites());
			view.updateFavMovieTable();
		}
	}
	public class ShowAllFavorites implements ActionListener
	{
		public void actionPerformed(ActionEvent arg0)
		{
			programModel.loadAllFavorites();
			view.updateFavMovieTable();
		}
	}
	public class MovieSelectListener implements ListSelectionListener
	{
		private JTable movieTable;
		private JTable actorTable;

		public MovieSelectListener(JTable movieTable, JTable actorTable)
		{
			this.movieTable = movieTable;
			this.actorTable = actorTable;
		}

		public void valueChanged(ListSelectionEvent e)
		{
			if(!e.getValueIsAdjusting())
			{
				try {
					if (movieTable.getSelectedRow() > -1)
					{
						MovieViewHelper mvh = (MovieViewHelper) movieTable.getModel();
						int index = movieTable.convertRowIndexToModel(movieTable.getSelectedRow());
						programModel.loadActorsByMovie(mvh.getValueAt(index));
						AbstractTableModel ATM = (AbstractTableModel) actorTable.getModel();
						ATM.fireTableDataChanged();
					}
				} catch (InOutException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
			}

		}

	}

	public class ActorSelectListener implements ListSelectionListener
	{
		private JTable movieTable;
		private JTable actorTable;

		public ActorSelectListener(JTable movieTable, JTable actorTable)
		{
			this.movieTable = movieTable;
			this.actorTable = actorTable;
		}

		public void valueChanged(ListSelectionEvent e)
		{
			if(!e.getValueIsAdjusting())
			{
				try {
					if (view.getActorTable().getSelectedRow() > -1)
					{
						ActorViewHelper avh = (ActorViewHelper) actorTable.getModel();
						int index = actorTable.convertRowIndexToModel(actorTable.getSelectedRow());
						programModel.loadMoviesByActor(avh.getValueAt(index));
						AbstractTableModel ATM = (AbstractTableModel) movieTable.getModel();
						ATM.fireTableDataChanged();
					}
				} catch (InOutException e1) {
					view.showError(e1.getMessage());
				}
			}
			
		}
	}

	public class MovieRateListener implements ActionListener
	{
		JTable movTable;
		List<Movie> movies;

		public MovieRateListener(JTable movTable, List<Movie> movies)
		{
			this.movies = movies;
			this.movTable = movTable;
		}

		public void actionPerformed(ActionEvent arg0)
		{
			if (movTable.getSelectedRowCount() == 1)
			{
				int state = view.rateDialog();
				double userRating = 0;
				if (state == JOptionPane.OK_OPTION)
				{
					try{
						userRating = Double.parseDouble(view.getRating());
					}catch (NumberFormatException e){
						view.showError("Invalid input!");
					}
					try{
						MovieViewHelper MVH = (MovieViewHelper)movTable.getModel();
						Movie mov=MVH.getValueAt(movTable.convertRowIndexToModel(movTable.getSelectedRow()));
						programModel.rateMovie(mov,userRating);
					}
					catch (RatingOutOfBound e){
						view.showError(e.getMessage());
					}
					catch (InOutException e){
						view.showError(e.getMessage());
					}catch (AlreadyRated e)
					{
						view.showError(e.getMessage());
					}
					view.updateMovieTable();
					view.updateFavMovieTable();
				}
			}
			else
			{
				view.showError("Exactly one movie should be selected!");
			}
		}
	}

	public class RemoveListener implements ActionListener
	{
		public void actionPerformed(ActionEvent e)
		{
			JTable favTable=view.getFavMovieTable();
			if (favTable.getSelectedRowCount() == 1)
			{
				try{
					MovieViewHelper MVH = (MovieViewHelper)favTable.getModel();
					programModel.removeFromFavorites(MVH.getValueAt(favTable.convertRowIndexToModel(favTable.getSelectedRow())));
				} catch (InOutException e1) {
					view.showError("Error while trying to remove the selected movie from your favorites.");
				}
				view.updateFavMovieTable();
			}
			else
			{
				view.showError("Exactly one movie should be selected!");
			}

		}
	}

	public class SaveListener implements ActionListener
	{
		public void actionPerformed(ActionEvent e)
		{
			if (view.getMovieTable().getSelectedRowCount() == 1)
			{
				try {
					MovieViewHelper MVH = (MovieViewHelper)view.getMovieTable().getModel();
					programModel.addMovieToFavorites(MVH.getValueAt(view.getMovieTable().convertRowIndexToModel(view.getMovieTable().getSelectedRow())));
				} catch (InOutException e1) {
					view.showError(e1.getMessage());
				} catch (AlreadyFavourite e1) {
					view.showError(e1.getMessage());
				}
				view.updateFavMovieTable();
			}
			else
			{
				view.showError("Exactly one movie should be selected!");
			}
		}
	}

	public class TabListener implements ChangeListener
	{

		public void stateChanged(ChangeEvent arg0)
		{
			view.getMovieTable().clearSelection();
			view.getActorTable().clearSelection();
			view.getFavMovieTable().clearSelection();
			view.getFavActorTable().clearSelection();
		}

	}
}
